apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sanjoy-app-1
  namespace: default
spec:
  interval: 15m
  path: "./fluxcd/repositories/sanjoy-app-1/deploy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: sanjoy-app-1
